# Generated by Django 5.2.3 on 2025-06-25 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя тэга')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255)),
                ('content', models.TextField(blank=True, verbose_name='Текст блога')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag', verbose_name='Тэги')),
            ],
            options={
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['create_time'], name='blog_blog_create__203d93_idx')],
            },
        ),
    ]
