# Generated by Django 5.2.3 on 2025-06-26 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blog',
            name='blog_blog_create__203d93_idx',
        ),
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-create_time'], name='blog_blog_create__4322d0_idx'),
        ),
    ]
