# Generated by Django 5.2.3 on 2025-06-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='word',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
