# Generated by Django 5.2.3 on 2025-08-04 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('translation', models.CharField(max_length=255, verbose_name='Перевод')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
