# Generated by Django 5.2.3 on 2025-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='words',
            options={'ordering': ['level']},
        ),
        migrations.AlterField(
            model_name='words',
            name='create_time',
            field=models.DateField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='words',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
