# Generated by Django 5.2.3 on 2025-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_words_options_alter_words_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Слово'),
        ),
    ]
