# Generated by Django 5.2.3 on 2025-08-24 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_words_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='slug',
        ),
        migrations.AlterField(
            model_name='words',
            name='person',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ws', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
